name: multi_cloud_storage
description: A Flutter plugin for multi-cloud storage that supports Google Drive, iCloud, Dropbox, and OneDrive.
version: 0.0.1
homepage: https://github.com/yourusername/multi_cloud_storage

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^14.0.0
  googleapis_auth: ^1.4.1
  dropbox_client: ^1.1.2
  flutter_onedrive: ^1.7.0
  icloud_storage_sync: ^0.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.multi_cloud_storage
        pluginClass: MultiCloudStoragePlugin
      ios:
        pluginClass: MultiCloudStoragePlugin
      macos:
        pluginClass: MultiCloudStoragePlugin
      windows:
        pluginClass: MultiCloudStoragePlugin
      linux:
        pluginClass: MultiCloudStoragePlugin

dependency_overrides:
  http: ^1.3.0