name: multi_cloud_storage_platform_interface
description: Platform interface for the multi_cloud_storage package.
version: 0.1.0
homepage: https://github.com/chris-wolf/multi_cloud_storage

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
